version: '3.9'

services:

  prometheus:
    image: prom/prometheus
    user: root
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
    env_file:
      - .env

  grafana:
    image: grafana/grafana
    user: root
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    networks:
      monitoring:
        aliases:
          - grafana
    env_file:
      - .env

networks:
  monitoring: