version: '3.9'

volumes:
  postgres_data:

services:

  storage:
    image: 'postgres:15.3'
    container_name: storage
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: [ 'CMD-SHELL', 'su postgres', '&&', 'pg_isready' ]
      interval: 5s
      timeout: 5s
      retries: 20
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  kpoint-back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kpoint-back
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - OAUTH2_REDIRECT_URI=${OAUTH2_REDIRECT_URI}
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -f http://localhost:${SERVER_PORT}/actuator/health || exit 1',
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s
    depends_on:
      storage:
        condition: service_healthy
    volumes:
      - '/etc/localtime:/etc/localtime:ro'

  kpoint-react:
    build:
      context: ./../kpoint-react
      dockerfile: Dockerfile.prod
      args:
        REACT_APP_API_PATH: ${BACK_API_PATH}
        REACT_APP_OAUTH2_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}

    container_name: kpoint-react
    depends_on:
      kpoint-back:
        condition: service_healthy
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
