email:
  subscription_mail:
    subject: Підписка на проект
    text:
      Вітаємо! Ви підписались на оновлення проекту.
  update_project_mail:
    subject: Оновлення проекту
    text:
      Вітаємо! У проекті, на який ви підписались, відбулись зміни!
