email:
  subscription_mail:
    subject: Підписка на проєкт
    text:
      Вітаємо! Ви підписались на оновлення проєкту.
  unsubscription_mail:
    subject: Відписка від проєкту
    text: Ви більше не підписані на оновлення проєкту.
  update_project_mail:
    subject: Оновлення проєкту
    text:
      Вітаємо! У проєкті, на який ви підписались, відбулись зміни!
