apiVersion: 1

datasources:
  # set the local prometheus instance as a datasource
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: true